#%%---%%
# Warning: portions of this code were automatically generated by Pydonia
# attempting to edit the raw Python code may lead to undefined behavior
# upon loading back into a Pydonia environment
import sympy as sp

x, y, z = sp.symbols("x y z")
#%%---%%
print("Test")
#---
