#%%---%%
# Warning: portions of this code were automatically generated by Pydonia
# attempting to edit the raw Python code may lead to undefined behavior
# upon loading back into a Pydonia environment. hi
import sympy as sp

x, y, z = sp.symbols("x y z")
print("Preamble")

#%%---%%
f = x**2 + y**2 + z**2 # comment

print(sp.integrate(f, (x, 0, 10))) 
print(sp.latex(f)) # f
print(sp.latex(sp.integrate(f, (x, 0, 10))))
#---
q = 1
if q==0:
	print("Bart Simpson")
else:
	print("Homer")
#---
if q==0:
	print()
	print("2")
print("3")
#---
# hi
print("Testing")
#---
print("Test3")
#---
print("Test7")
#---
print("Test8")
#---
print("Test9")
#---
print("Test10")
#---
# best of
#---
print("Hi in latex")
#---
g = x**2/(17*x)
print(sp.latex(g))
print(sp.latex(sp.integrate(g, (x, 0, 20))))
#---
hi
#---
print(x+2 == f)
#---

#---
