#%%---%%
# Warning: portions of this code were automatically generated by Pydonia
# attempting to edit the raw Python code may lead to undefined behavior
# upon loading back into a Pydonia environment
import sympy as sp

x, y, z = sp.symbols("x y z")
#%%---%%
import sys
import time

from PyQt5.QtCore import (QCoreApplication, QObject, QRunnable, QThread,
                          QThreadPool, pyqtSignal)

# Subclassing QObject and using moveToThread
# http://blog.qt.digia.com/blog/2007/07/05/qthreads-no-longer-abstract
class SomeObject(QObject):

    finished = pyqtSignal()

    def long_running(self):
        count = 0
        while count < 5:
            time.sleep(1)
            print("B Increasing")
            count += 1
        self.finished.emit()


def using_move_to_thread():
    app = QCoreApplication([])
    objThread = QThread()
    obj = SomeObject()
    obj.moveToThread(objThread)
    obj.finished.connect(objThread.quit)
    objThread.started.connect(obj.long_running)
    objThread.finished.connect(app.exit)
    objThread.start()
    sys.exit(app.exec_())

if __name__ == "__main__":
    #using_q_thread()
    using_move_to_thread()
    #using_q_runnable()