#%%---%%
# Warning: portions of this code were automatically generated by Pydonia
# attempting to edit the raw Python code may lead to undefined behavior
# upon loading back into a Pydonia environment. hi
import sympy as sp

x, y, z = sp.symbols("x y z")
print("Preamble")

#%%---%%
f = x**2 + y**2 + z**2 # comment

print(sp.integrate(f, (x, 0, 10))) 
print(sp.latex(f)) #s
print(sp.latex(sp.integrate(f, (x, 0, 10))))
#---
x = 1
if x==0:
	print("Bart Simpson")
else:
	print("Homer")
#---
if x==0:
	print()
	print("2")
print("3")
#---
# hi
print("Testing")
print("Testing")
#---

#---
print("Test3")
#---
print("Test7")
#---
print("Test8")
#---
print("Test9")
#---
print("Test10")
#---
# best of