#%%---%%
# Warning: portions of this code were automatically generated by Pydonia
# attempting to edit the raw Python code may lead to undefined behavior
# upon loading back into a Pydonia environment
import sympy as sp

x, y, z = sp.symbols("x y z")
#%%---%%
# codeCapture.py
import io
import traceback
from contextlib import redirect_stdout, redirect_stderr
import code
from PyQt6.QtCore import QThread, pyqtSignal, QObject

class CodeCapture(QObject):
    output = pyqtSignal(str)
    finished = pyqtSignal()

    def __init__(self, console: code.InteractiveConsole, source: str):
        super().__init__()
        self.source = source
        self.console = console

    def run(self):
        console = self.console

        try:
            codeobj = compile(self.source, "<string>", "exec")
        except Exception:
            tb = traceback.format_exc()
            self.output.emit(tb)
            return  # stop — can't runcode without codeobj

        buf = io.StringIO()
        with redirect_stdout(buf), redirect_stderr(buf):
            try:
                console.runcode(codeobj)
            except Exception:
                # runcode may call showtraceback already, but ensure we capture any other
                buf.write("\n" + traceback.format_exc())

        self.output.emit(buf.getvalue())

