# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\WindowDesign.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PydoniaMainWindow(object):
    def setupUi(self, PydoniaMainWindow):
        PydoniaMainWindow.setObjectName("PydoniaMainWindow")
        PydoniaMainWindow.resize(549, 356)
        self.centralwidget = QtWidgets.QWidget(PydoniaMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Button1 = QtWidgets.QPushButton(self.centralwidget)
        self.Button1.setGeometry(QtCore.QRect(180, 90, 191, 111))
        self.Button1.setObjectName("Button1")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(80, 90, 78, 20))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(80, 120, 78, 20))
        self.checkBox_2.setObjectName("checkBox_2")
        self.Label1 = QtWidgets.QLabel(self.centralwidget)
        self.Label1.setGeometry(QtCore.QRect(210, 50, 71, 16))
        self.Label1.setObjectName("Label1")
        PydoniaMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(PydoniaMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 549, 33))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        PydoniaMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(PydoniaMainWindow)
        self.statusbar.setObjectName("statusbar")
        PydoniaMainWindow.setStatusBar(self.statusbar)
        self.actionmenu = QtWidgets.QAction(PydoniaMainWindow)
        self.actionmenu.setObjectName("actionmenu")
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionmenu)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(PydoniaMainWindow)
        QtCore.QMetaObject.connectSlotsByName(PydoniaMainWindow)

    def retranslateUi(self, PydoniaMainWindow):
        _translate = QtCore.QCoreApplication.translate
        PydoniaMainWindow.setWindowTitle(_translate("PydoniaMainWindow", "Pydonia"))
        self.Button1.setText(_translate("PydoniaMainWindow", "Click"))
        self.checkBox.setText(_translate("PydoniaMainWindow", "CheckBox"))
        self.checkBox_2.setText(_translate("PydoniaMainWindow", "CheckBox"))
        self.Label1.setText(_translate("PydoniaMainWindow", "Hello Tim"))
        self.menuFile.setTitle(_translate("PydoniaMainWindow", "File"))
        self.actionmenu.setText(_translate("PydoniaMainWindow", "menu"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PydoniaMainWindow = QtWidgets.QMainWindow()
    ui = Ui_PydoniaMainWindow()
    ui.setupUi(PydoniaMainWindow)
    PydoniaMainWindow.show()
    sys.exit(app.exec_())
