# Form implementation generated from reading ui file '.\QtTutorial\WindowDesign.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QMessageBox


class Ui_PydoniaMainWindow(object):
    def setupUi(self, PydoniaMainWindow):
        PydoniaMainWindow.setObjectName("PydoniaMainWindow")
        PydoniaMainWindow.resize(549, 356)
        self.centralwidget = QtWidgets.QWidget(parent=PydoniaMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Button1 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Button1.setGeometry(QtCore.QRect(180, 90, 191, 111))
        self.Button1.setObjectName("Button1")
        self.checkBox = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(80, 90, 78, 20))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(80, 120, 78, 20))
        self.checkBox_2.setObjectName("checkBox_2")
        self.Label1 = QtWidgets.QLabel(parent=self.centralwidget)
        self.Label1.setGeometry(QtCore.QRect(210, 50, 71, 16))
        self.Label1.setObjectName("Label1")
        PydoniaMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=PydoniaMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 549, 33))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(parent=self.menubar)
        self.menuFile.setObjectName("menuFile")
        PydoniaMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=PydoniaMainWindow)
        self.statusbar.setObjectName("statusbar")
        PydoniaMainWindow.setStatusBar(self.statusbar)
        self.actionmenu = QtGui.QAction(parent=PydoniaMainWindow)
        self.actionmenu.setObjectName("actionmenu")
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionmenu)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(PydoniaMainWindow)
        QtCore.QMetaObject.connectSlotsByName(PydoniaMainWindow)

        self.Button1.clicked.connect(self.show_popup)

    def retranslateUi(self, PydoniaMainWindow):
        _translate = QtCore.QCoreApplication.translate
        PydoniaMainWindow.setWindowTitle(_translate("PydoniaMainWindow", "Pydonia"))
        self.Button1.setText(_translate("PydoniaMainWindow", "Click"))
        self.checkBox.setText(_translate("PydoniaMainWindow", "CheckBox"))
        self.checkBox_2.setText(_translate("PydoniaMainWindow", "CheckBox"))
        self.Label1.setText(_translate("PydoniaMainWindow", "Hello Tim"))
        self.menuFile.setTitle(_translate("PydoniaMainWindow", "File"))
        self.actionmenu.setText(_translate("PydoniaMainWindow", "menu"))

    def show_popup(self):
        msg = QMessageBox()
        msg.setWindowTitle("Message Box Example")
        msg.setText("Thsi is the message")
        msg.setInformativeText("Informative Text")
        msg.setDetailedText("Detail text")

        #msg.setIcon(QMessageBox.Icon.Critical)
        #msg.setIcon(QMessageBox.Icon.Warning)
        #msg.setIcon(QMessageBox.Icon.Information)
        msg.setIcon(QMessageBox.Icon.Question)

        msg.setStandardButtons(QMessageBox.StandardButton.Ok|QMessageBox.StandardButton.Yes|QMessageBox.StandardButton.No|QMessageBox.StandardButton.Abort|QMessageBox.StandardButton.Ignore) # OK Open Save Cancel Close Yes No Abort Retry Ignore
        msg.setDefaultButton(QMessageBox.StandardButton.Yes)

        msg.buttonClicked.connect(self.popup_button)

        x = msg.exec() # makes the popup apear

    def popup_button(self, i):
        print(i.text())


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PydoniaMainWindow = QtWidgets.QMainWindow()
    ui = Ui_PydoniaMainWindow()
    ui.setupUi(PydoniaMainWindow)
    PydoniaMainWindow.show()
    sys.exit(app.exec())
