# Form implementation generated from reading ui file '.\QtTutorial\Images.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

import PyQt6
from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QSizePolicy
from PyQt6.uic import loadUi


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(730, 577)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.photo = QtWidgets.QLabel(parent=self.centralwidget)
        self.photo.setGeometry(QtCore.QRect(10, 10, 711, 391))
        self.photo.setText("")
        self.photo.setPixmap(QtGui.QPixmap("./Images/Screenshot 2025-03-13 034016.png"))
        self.photo.setScaledContents(True)
        self.photo.setObjectName("photo")
        self.Cat = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Cat.setGeometry(QtCore.QRect(28, 440, 311, 61))
        self.Cat.setObjectName("Cat")
        self.Dog = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Dog.setGeometry(QtCore.QRect(340, 440, 361, 61))
        self.Dog.setObjectName("Dog")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 730, 33))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.Dog.clicked.connect(lambda: self.showIMG("./Images/WIN_20250301_20_26_27_Pro.jpg"))
        self.Cat.clicked.connect(lambda: self.showIMG("./Images/Screenshot 2025-03-13 034016.png"))

        self.Cat.setSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Cat.setText(_translate("MainWindow", "Cat"))
        self.Dog.setText(_translate("MainWindow", "Dog"))

    def showIMG(self, path):
        self.photo.setPixmap(QtGui.QPixmap(path))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    # app.setWindowIcon(PyQt6.QtGui.QIcon("./QtTutorial/Icon.jpg"))
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
